#!/usr/bin/env bash

DIR=`pwd`
DIMAGE=abulovic/sysbio-docker

if [ ! -d "$DIR/models" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir $DIR/models
fi

if [ ! -d "$DIR/sim-output" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir $DIR/sim-output
fi

if [ ! -d "$DIR/plots" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir $DIR/plots
fi

docker run -ti -v $DIR/models/:/home/sysbio/models -v $DIR/sim-output/:/home/sysbio/sim-output $DIMAGE
