#!/usr/bin/env python

import os
import io
import nbformat.v4 as nbv4
from argparse import ArgumentParser


_imports = '''import os, sys

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.graph_objs import Scatter, Figure, Layout

from sysbio import run_simulation, plot_timecourse'''

_setup = '''init_notebook_mode(connected=True)'''

_ddir = 'data_dir = "."'

_simulate = 'plots = run_simulation("%(mfile)s", "%(format)s")'

_plot = '''for plot in plots:
    plot_timecourse(plot)'''

def get_parser():
    parser = ArgumentParser()
    parser.add_argument("model", help="Path to model file")
    parser.add_argument("format", help="Model format")
    return parser


if __name__ == '__main__':

    parser = get_parser()
    args = parser.parse_args()
    model = args.model
    mname = model.split('/')[-1].split('.')[0]
    _format = args.format

    notebook_name = '%s-plots' % mname

    notebook = nbv4.new_notebook()
    notebook
    notebook['cells'].append(nbv4.new_code_cell(_imports))
    notebook['cells'].append(nbv4.new_code_cell(_setup))
    notebook['cells'].append(nbv4.new_code_cell(_ddir))
    notebook['cells'].append(nbv4.new_code_cell(_simulate % {
        'mfile': model,
        'format': _format,
        }
    ))
    
    notebook['cells'].append(nbv4.new_code_cell(_plot))

    with io.open('/data/%(name)s.ipynb' % {'name': notebook_name}, 'w', encoding='utf-8') as f:
        f.write(nbv4.writes(notebook))

    print '/data/%(name)s.ipynb' % {'name': notebook_name}
