#! /usr/bin/env python
import os
import sys
import json
import shutil
from argparse import ArgumentParser
from datetime import datetime as dtime

import roadrunner
import tellurium as te

_default_cfg = '''
{
	"integration": {
		"stiff": true
	},
	"plotting": {
		"timecourse": {
			"plot-all": true,
			"plot-groups": false
		}
	}
}
'''



class Config(object):

	def __init__(self, fname, model):
		if not fname:
			_json_str = _default_cfg
		else:
			with open(fname) as fin:
				_json_str = ''.join(fin.readlines())
		self.model = model
		self._load_cfg(_json_str)

	def _load_cfg(self, json_str):
		self._opts = json.loads(json_str)
		if self._opts['plotting']['timecourse']['plot-all']:
			species = [str(val) for val in self.model.getStateVectorIds()]
			if 'groups' not in self._opts['plotting']['timecourse']:
				self._opts['plotting']['timecourse']['groups'] = {}
			self._opts['plotting']['timecourse']['groups']['All_species'] = {"species": species}

		if 'steady-state' in self._opts['plotting']:
			if self._opts['plotting']['steady-state']['plot-all']:
				species = [str(val) for val in self.model.getStateVectorIds()]
				if 'groups' not in self._opts['plotting']['steady-state']:
					self._opts['plotting']['steady-state']['groups'] = {}
				self._opts['plotting']['steady-state']['groups']['All_ss_species'] = {'species': species}

		self.species = self.get_species_list()
		self.ss_species = self.get_ss_species_list()


	def get_timecourse_options(self):
		if 'selections' not in self._opts['integration']:
			self._opts['integration']['selections'] = self.species
		return self._opts['integration']

	def get_species_list(self):
		if self._opts['plotting']['timecourse']['plot-all']:
			selection = self.model.getStateVectorIds()
		elif self._opts['plotting']['timecourse']['plot-groups']:
			selection = []
			for gid, gval in self._opts['plotting']['timecourse']['groups'].items():
				selection.extend(gval['species'])
		return ['time'] + [str(val) for val in selection]

	def get_ss_species_list(self):
		selection = []
		if 'steady-state' not in self._opts['plotting']:
			return []
		if self._opts['plotting']['steady-state']['plot-all']:
			selection = self.model.getStateVectorIds()
		elif self._opts['plotting']['steady-state']['plot-groups']:
			selection = []
			for gid, gval in self._opts['plotting']['steady-state']['groups'].items():
				selection.extend(gval['species'])
		return [str(val) for val in selection]


	def get_timecourse_plots(self):
		return self._opts['plotting']['timecourse']['groups']

	def get_steady_state_plots(self):
		if 'steady-state' in self._opts['plotting']:
			return self._opts['plotting']['steady-state']['groups']
		else:
			return {}


def get_parser():
	parser = ArgumentParser()
	parser.add_argument('model', help='Model file')
	parser.add_argument('format', help='Model format')
	parser.add_argument('action', choices=['sim', 'list-plots'])
	return parser

def get_timecourse(result, species, all_species, name):
	return result[:, all_species.index(name)]

def export_sim(cfg, result, ss_result, out_dir):
	for name, opts in cfg.get_timecourse_plots().items():
		with open(os.path.sep.join([out_dir, '%s.txt' % name]), 'w') as fout:
			species = ['time'] + opts["species"]
			for sp in species:
				res = get_timecourse(result, species, cfg.species, sp)
				fout.write('%s;%s\n' % (sp, ';'.join([str(val) for val in res])))

	for name, opts in cfg.get_steady_state_plots().items():
		with open(os.path.sep.join([out_dir, 'SS-%s.txt' % name]), 'w') as fout:
			species = opts["species"]
			for sp, val in zip(species, ss_result):
				fout.write('%s;%s\n' % (sp, str(val)))

def _is_int(_str):
	try:
		int(_str)
		return True
	except Exception, e:
		return False


def create_directory_structure(mfile, cfile, cfg):
	mname = cfg.model.getModelName().replace(' ', '_')
	topdir = '/data/%s' % mname
	if not os.path.isdir(topdir):
		os.makedirs(topdir)
	simdirs = map(lambda f: int(f), filter(lambda f: _is_int(f), os.listdir(topdir)))
	simdirs.append(0)
	new_simdir = max(simdirs) + 1

	abs_simdir = '%s/%d' % (topdir, new_simdir)
	os.makedirs(abs_simdir)

	shutil.copy(mfile, abs_simdir)
	if cfile:
		shutil.copy(cfile, abs_simdir)

	return abs_simdir

def simulate(model, _format):
	os.chdir('/data/models')

	model_name = model.split('/')[-1].split('.')[0]
	cfg_file = '/data/models/%(mname)s.cfg' % {'mname': model_name}

	if _format == 'sbml':
		rr = roadrunner.RoadRunner(model)
	elif _format == 'antimony':
		with open(model) as fin:
			rr = te.loada(fin.read())

	if not os.path.isfile(cfg_file):
		cfg_file = None
	cfg = Config(cfg_file, rr.getModel())

	result = rr.simulate(**cfg.get_timecourse_options())


	if cfg.ss_species:
		rr.steadyStateSelections = cfg.ss_species
		ss_result = rr.getSteadyStateValues()
	else:
		ss_result = None


	outdir = create_directory_structure(model, cfg_file, cfg)

	export_sim(cfg, result, ss_result, outdir)

	print outdir

def list_plots(model, _format):

	os.chdir('/data/models')

	model_name = model.split('/')[-1].split('.')[0]
	cfg_file = '/data/models/%(mname)s.cfg' % {'mname': model_name}

	if _format == 'sbml':
		rr = roadrunner.RoadRunner(model)
	elif _format == 'antimony':
		with open(model) as fin:
			rr = te.loada(fin.read())

	if not os.path.isfile(cfg_file):
		cfg_file = None
	cfg = Config(cfg_file, rr.getModel())

	print '\n'.join(cfg.get_timecourse_plots().keys())
	print '\n'.join(['SS-%s' % plot for plot in cfg.get_steady_state_plots().keys()])


def main():

	parser = get_parser()
	args = parser.parse_args()

	if args.action == 'sim':
		simulate(args.model, args.format)

	elif args.action == 'list-plots':
		list_plots(args.model, args.format)


	


if __name__ == '__main__':
	main()
